version: '3.8'

services:
        # Descrevendo o serviço do Nginx
        web:
                image: nginx:latest
                container_name: aplicacao
                ports:
                        - "8080:80"
                volumes:
                        - ./site:/site
                        - ./nginx.conf:/etc/nginx/conf.d/default.conf
                networks:
                        - site-network
networks:
        site-network:
                driver: bridge
